title: WFDB
theme: just-the-docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag

callouts:
  warning:
    title: Note
    color: red
  important:
    title: Note
    color: blue
  citation:
    title: Citation
    color: yellow

footer_content: |
  For more accessibility options, see the <a href="https://accessibility.mit.edu/" target="_blank" rel="noopener">MIT Accessibility Page</a>.