title: WFDB
theme: just-the-docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag

callouts:
  warning:
    title: Note
    color: red
  important:
    title: Note
    color: blue
  citation:
    title: Citation
    color: yellow